In [3]:
!python neat_test.py


[***]	Fitness: [720.91]


In [4]:
from neat_src.ann import getNodeOrder

import numpy as np

# Create a more complex network with multiple hidden nodes and connections
nodeG = np.array([
    [5, 6, 7, 8, 9, 10],     # Node IDs: 1 input, 1 bias, 1 output, 3 hidden
    [1, 4, 2, 3, 3, 3],      # Node types: 5=input, 6=bias, 7=output, rest hidden
    [1, 1, 1, 1, 1, 1]       # Activation functions (1 = linear)
])

connG = np.array([
    [1, 2, 3, 4, 5, 6],      # Innovation numbers
    [5, 6, 8, 9, 8, 10],     # Source nodes
    [8, 8, 9, 7, 10, 7],     # Destination nodes
    [0.5, 0.3, 0.2, 0.4, 0.6, 0.1],  # Weights
    [1, 1, 1, 1, 1, 1]       # All enabled
])

# Test the function
Q, wMat = getNodeOrder(nodeG, connG)
print("Node order Q:", Q)
print("\nWeight Matrix:")
print(wMat)

Node order Q: [0 1 3 4 5 2]

Weight Matrix:
[[0.  0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.3 0.  0. ]
 [0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.  1. ]
 [0.  0.  0.4 0.  0.  0. ]
 [0.  0.  0.1 0.  0.  0. ]]


In [6]:
from neat_src.ann import getLayer 

getLayer(wMat)

array([0., 0., 3., 1., 2., 2.])

In [1]:
from neat_src.ind import Ind 

import numpy as np

# Create a more complex network with multiple hidden nodes and connections
nodeG = np.array([
    [5, 6, 7, 8, 9, 10],     # Node IDs: 1 input, 1 bias, 1 output, 3 hidden
    [1, 4, 2, 3, 3, 3],      # Node types: 5=input, 6=bias, 7=output, rest hidden
    [1, 1, 1, 1, 1, 1]       # Activation functions (1 = linear)
])

connG = np.array([
    [1, 2, 3, 4, 5, 6],      # Innovation numbers
    [5, 6, 8, 9, 8, 10],     # Source nodes
    [8, 8, 9, 7, 10, 7],     # Destination nodes
    [0.5, 0.3, 0.2, 0.4, 0.6, 0.1],  # Weights
    [1, 1, 1, 1, 1, 1]       # All enabled
])

innov = np.array([
    [1],      # Innovation Number
    [5],      # Source node
    [8],      # Destination node
    [-1],     # New Node? (-1 indicates no new node)
    [0]       # Generation evolved
])

individual = Ind(connG, nodeG)

In [7]:
p = {"ann_absWCap": 0.5, "ann_actRange": [1, 2]}
# individual.mutAddConn(connG, nodeG, innov, 1, p) # takes forever -- likely into infinite loop ... 
individual.mutAddNode(connG, nodeG, innov, 1, p)

(array([[ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  2. ,  3. ],
        [ 5. ,  6. ,  8. ,  9. ,  8. , 10. ,  9. ,  9. ],
        [ 8. ,  8. ,  9. ,  7. , 10. ,  7. ,  9. ,  7. ],
        [ 0.5,  0.3,  0.2,  0.4,  0.6,  0.1,  1. ,  0.4],
        [ 1. ,  1. ,  1. ,  0. ,  1. ,  1. ,  1. ,  1. ]]),
 array([[ 5,  6,  7,  8,  9, 10,  9],
        [ 1,  4,  2,  3,  3,  3,  3],
        [ 1,  1,  1,  1,  1,  1,  1]]),
 array([[ 1.,  2.,  3.],
        [ 5.,  9.,  9.],
        [ 8.,  9.,  7.],
        [-1.,  9., -1.],
        [ 0.,  1.,  1.]]))